######################################################################
# Automatically generated by qmake (2.01a) Sk Vas 7 18:23:01 2010
######################################################################

include(../qmtp/qmtp.pro)

OTHER_HEADERS = $$HEADERS
OTHER_SOURCES = $$SOURCES

HEADERS = ""
SOURCES = ""

for(i, OTHER_HEADERS):HEADERS += "../qmtp/"$${i}
for(i, OTHER_SOURCES):SOURCES += "../qmtp/"$${i}

#message($$HEADERS)

CONFIG += qtestlib
TEMPLATE = app

DEFINES += -Wno-unused-parameter

INCLUDEPATH += ../qmtp

# Input
HEADERS += qmtptest.h
SOURCES += qmtptest.cpp


message($$LIBS)
message($$INCLUDEPATH)
